#!/usr/bin/env python3
"""
Interactive Supabase .env setup script
This will guide you through creating a .env file with Supabase connection
"""

import os
import secrets
import sys

def generate_secret_key(length=32):
    """Generate a secure random key"""
    return secrets.token_urlsafe(length)

def print_header(text):
    """Print a formatted header"""
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60 + "\n")

def print_step(number, text):
    """Print a step number"""
    print(f"\n📍 Step {number}: {text}")
    print("-" * 60)

def main():
    print_header("🚀 Supabase + Cloud Run Environment Setup")

    print("This script will help you create a .env file for Supabase.")
    print("\nYou'll need:")
    print("  1. A Supabase account (https://supabase.com)")
    print("  2. A Supabase project created")
    print("  3. Your database connection string from Supabase")

    response = input("\n❓ Do you have a Supabase project ready? (yes/no): ")

    if response.lower() not in ['yes', 'y']:
        print("\n📝 Please follow these steps first:")
        print("   1. Go to https://supabase.com")
        print("   2. Sign up / Log in")
        print("   3. Create a new project")
        print("   4. Choose 'Southeast Asia (Singapore)' region")
        print("   5. Wait 2-3 minutes for setup to complete")
        print("   6. Come back and run this script again!")
        sys.exit(0)

    # Get database connection string
    print_step(1, "Get Database Connection String")
    print("\nIn Supabase Dashboard:")
    print("  1. Click 'Settings' (⚙️) in the sidebar")
    print("  2. Click 'Database'")
    print("  3. Scroll to 'Connection String'")
    print("  4. Select 'URI' tab")
    print("  5. Copy the connection string")
    print("\nIt looks like:")
    print("  postgresql://postgres:[YOUR-PASSWORD]@db.xxxxx.supabase.co:5432/postgres")

    database_url = input("\n📋 Paste your Supabase connection string here: ").strip()

    if not database_url:
        print("\n❌ Connection string cannot be empty!")
        sys.exit(1)

    # Validate and convert connection string
    if database_url.startswith('postgresql://'):
        # Convert to SQLAlchemy format
        database_url = database_url.replace('postgresql://', 'postgresql+psycopg2://')
        print("\n✅ Converted to SQLAlchemy format")
    elif not database_url.startswith('postgresql+psycopg2://'):
        print("\n⚠️  Warning: Connection string should start with 'postgresql://'")
        confirm = input("Continue anyway? (yes/no): ")
        if confirm.lower() not in ['yes', 'y']:
            sys.exit(1)

    # Check if password is still placeholder
    if '[YOUR-PASSWORD]' in database_url or 'YOUR-PASSWORD' in database_url:
        print("\n⚠️  Warning: You need to replace [YOUR-PASSWORD] with your actual password!")
        print("\nTo find your password:")
        print("  1. If you saved it during project creation, use that")
        print("  2. Otherwise, reset it in: Settings → Database → Reset Database Password")

        password = input("\n🔑 Enter your Supabase database password: ").strip()
        if password:
            database_url = database_url.replace('[YOUR-PASSWORD]', password)
            database_url = database_url.replace('YOUR-PASSWORD', password)

    # Environment selection
    print_step(2, "Select Environment")
    print("\n1. Development (local testing)")
    print("2. Production (Cloud Run deployment)")

    env_choice = input("\n❓ Choose environment (1 or 2): ").strip()

    if env_choice == '1':
        flask_env = 'development'
        debug = 'True'
        port = '8001'
        cors_origins = '*'
    else:
        flask_env = 'production'
        debug = 'False'
        port = '8080'
        print("\n❓ Enter your frontend URL (or press Enter for '*' to allow all):")
        cors_origins = input("   (e.g., https://your-app.vercel.app): ").strip() or '*'

    # Generate secret keys
    print_step(3, "Generate Security Keys")
    print("\nGenerating secure random keys...")

    jwt_secret = generate_secret_key(32)
    secret_key = generate_secret_key(32)

    print("✅ Generated JWT_SECRET_KEY")
    print("✅ Generated SECRET_KEY")

    # Create .env content
    env_content = f"""# Environment Configuration for Kos Dashboard
# Generated by setup_supabase_env.py

# ===== Application Settings =====
FLASK_ENV={flask_env}
DEBUG={debug}
PORT={port}

# ===== Security =====
SECRET_KEY={secret_key}
JWT_SECRET_KEY={jwt_secret}
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30

# ===== Database Configuration =====
# Supabase PostgreSQL Database
DATABASE_URL={database_url}

# ===== CORS Configuration =====
CORS_ORIGINS={cors_origins}

# ===== Application Info =====
APP_ENV={flask_env}
LOG_LEVEL=INFO
"""

    # Show preview
    print_step(4, "Preview Configuration")
    print("\n" + env_content)

    # Confirm
    confirm = input("\n❓ Save this configuration to .env? (yes/no): ")

    if confirm.lower() in ['yes', 'y']:
        # Backup existing .env
        if os.path.exists('.env'):
            backup_path = '.env.backup'
            counter = 1
            while os.path.exists(backup_path):
                backup_path = f'.env.backup.{counter}'
                counter += 1

            with open('.env', 'r') as f:
                old_content = f.read()

            with open(backup_path, 'w') as f:
                f.write(old_content)

            print(f"\n💾 Backed up existing .env to {backup_path}")

        # Write new .env
        with open('.env', 'w') as f:
            f.write(env_content)

        print("\n✅ Configuration saved to .env")

        # Next steps
        print_header("🎉 Setup Complete!")
        print("\n📋 Next Steps:")
        print("\n1. Test the connection:")
        print("   python3 create_admin.py")
        print("\n2. Create admin user (if prompted)")
        print("\n3. Run the application:")
        print("   python3 app.py")
        print("\n4. Test the API:")
        print("   curl http://localhost:8001/health")

        if env_choice == '2':
            print("\n5. Deploy to Cloud Run:")
            print("   cd ..")
            print("   gcloud run deploy kos-api --source ./backend --region=asia-southeast2")

        print("\n📚 Documentation:")
        print("   See SUPABASE_SETUP.md for full deployment guide")

    else:
        print("\n❌ Configuration not saved. Run the script again when ready.")
        sys.exit(1)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        sys.exit(1)
